package com.acido303.transactionflow.producer.generator;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Official ISO 3166-1 alpha-2 country codes (as published at
 * https://www.iban.com/country-codes). Used to validate countries added to
 * the generator so only real codes can be used.
 */
public final class IsoCountries {

    private IsoCountries() {}

    public static final Map<String, String> CODE_TO_NAME;

    static {
        Map<String, String> m = new LinkedHashMap<>();
        m.put("AF", "Afghanistan");
        m.put("AX", "Aland Islands");
        m.put("AL", "Albania");
        m.put("DZ", "Algeria");
        m.put("AS", "American Samoa");
        m.put("AD", "Andorra");
        m.put("AO", "Angola");
        m.put("AI", "Anguilla");
        m.put("AQ", "Antarctica");
        m.put("AG", "Antigua and Barbuda");
        m.put("AR", "Argentina");
        m.put("AM", "Armenia");
        m.put("AW", "Aruba");
        m.put("AU", "Australia");
        m.put("AT", "Austria");
        m.put("AZ", "Azerbaijan");
        m.put("BS", "Bahamas");
        m.put("BH", "Bahrain");
        m.put("BD", "Bangladesh");
        m.put("BB", "Barbados");
        m.put("BY", "Belarus");
        m.put("BE", "Belgium");
        m.put("BZ", "Belize");
        m.put("BJ", "Benin");
        m.put("BM", "Bermuda");
        m.put("BT", "Bhutan");
        m.put("BO", "Bolivia");
        m.put("BQ", "Bonaire, Sint Eustatius and Saba");
        m.put("BA", "Bosnia and Herzegovina");
        m.put("BW", "Botswana");
        m.put("BV", "Bouvet Island");
        m.put("BR", "Brazil");
        m.put("IO", "British Indian Ocean Territory");
        m.put("BN", "Brunei Darussalam");
        m.put("BG", "Bulgaria");
        m.put("BF", "Burkina Faso");
        m.put("BI", "Burundi");
        m.put("CV", "Cabo Verde");
        m.put("KH", "Cambodia");
        m.put("CM", "Cameroon");
        m.put("CA", "Canada");
        m.put("KY", "Cayman Islands");
        m.put("CF", "Central African Republic");
        m.put("TD", "Chad");
        m.put("CL", "Chile");
        m.put("CN", "China");
        m.put("CX", "Christmas Island");
        m.put("CC", "Cocos (Keeling) Islands");
        m.put("CO", "Colombia");
        m.put("KM", "Comoros");
        m.put("CG", "Congo");
        m.put("CD", "Congo, Democratic Republic of the");
        m.put("CK", "Cook Islands");
        m.put("CR", "Costa Rica");
        m.put("CI", "Cote d'Ivoire");
        m.put("HR", "Croatia");
        m.put("CU", "Cuba");
        m.put("CW", "Curacao");
        m.put("CY", "Cyprus");
        m.put("CZ", "Czechia");
        m.put("DK", "Denmark");
        m.put("DJ", "Djibouti");
        m.put("DM", "Dominica");
        m.put("DO", "Dominican Republic");
        m.put("EC", "Ecuador");
        m.put("EG", "Egypt");
        m.put("SV", "El Salvador");
        m.put("GQ", "Equatorial Guinea");
        m.put("ER", "Eritrea");
        m.put("EE", "Estonia");
        m.put("SZ", "Eswatini");
        m.put("ET", "Ethiopia");
        m.put("FK", "Falkland Islands (Malvinas)");
        m.put("FO", "Faroe Islands");
        m.put("FJ", "Fiji");
        m.put("FI", "Finland");
        m.put("FR", "France");
        m.put("GF", "French Guiana");
        m.put("PF", "French Polynesia");
        m.put("TF", "French Southern Territories");
        m.put("GA", "Gabon");
        m.put("GM", "Gambia");
        m.put("GE", "Georgia");
        m.put("DE", "Germany");
        m.put("GH", "Ghana");
        m.put("GI", "Gibraltar");
        m.put("GR", "Greece");
        m.put("GL", "Greenland");
        m.put("GD", "Grenada");
        m.put("GP", "Guadeloupe");
        m.put("GU", "Guam");
        m.put("GT", "Guatemala");
        m.put("GG", "Guernsey");
        m.put("GN", "Guinea");
        m.put("GW", "Guinea-Bissau");
        m.put("GY", "Guyana");
        m.put("HT", "Haiti");
        m.put("HM", "Heard Island and McDonald Islands");
        m.put("VA", "Holy See");
        m.put("HN", "Honduras");
        m.put("HK", "Hong Kong");
        m.put("HU", "Hungary");
        m.put("IS", "Iceland");
        m.put("IN", "India");
        m.put("ID", "Indonesia");
        m.put("IR", "Iran");
        m.put("IQ", "Iraq");
        m.put("IE", "Ireland");
        m.put("IM", "Isle of Man");
        m.put("IL", "Israel");
        m.put("IT", "Italy");
        m.put("JM", "Jamaica");
        m.put("JP", "Japan");
        m.put("JE", "Jersey");
        m.put("JO", "Jordan");
        m.put("KZ", "Kazakhstan");
        m.put("KE", "Kenya");
        m.put("KI", "Kiribati");
        m.put("KP", "Korea, Democratic People's Republic of");
        m.put("KR", "Korea, Republic of");
        m.put("KW", "Kuwait");
        m.put("KG", "Kyrgyzstan");
        m.put("LA", "Lao People's Democratic Republic");
        m.put("LV", "Latvia");
        m.put("LB", "Lebanon");
        m.put("LS", "Lesotho");
        m.put("LR", "Liberia");
        m.put("LY", "Libya");
        m.put("LI", "Liechtenstein");
        m.put("LT", "Lithuania");
        m.put("LU", "Luxembourg");
        m.put("MO", "Macao");
        m.put("MG", "Madagascar");
        m.put("MW", "Malawi");
        m.put("MY", "Malaysia");
        m.put("MV", "Maldives");
        m.put("ML", "Mali");
        m.put("MT", "Malta");
        m.put("MH", "Marshall Islands");
        m.put("MQ", "Martinique");
        m.put("MR", "Mauritania");
        m.put("MU", "Mauritius");
        m.put("YT", "Mayotte");
        m.put("MX", "Mexico");
        m.put("FM", "Micronesia");
        m.put("MD", "Moldova");
        m.put("MC", "Monaco");
        m.put("MN", "Mongolia");
        m.put("ME", "Montenegro");
        m.put("MS", "Montserrat");
        m.put("MA", "Morocco");
        m.put("MZ", "Mozambique");
        m.put("MM", "Myanmar");
        m.put("NA", "Namibia");
        m.put("NR", "Nauru");
        m.put("NP", "Nepal");
        m.put("NL", "Netherlands");
        m.put("NC", "New Caledonia");
        m.put("NZ", "New Zealand");
        m.put("NI", "Nicaragua");
        m.put("NE", "Niger");
        m.put("NG", "Nigeria");
        m.put("NU", "Niue");
        m.put("NF", "Norfolk Island");
        m.put("MK", "North Macedonia");
        m.put("MP", "Northern Mariana Islands");
        m.put("NO", "Norway");
        m.put("OM", "Oman");
        m.put("PK", "Pakistan");
        m.put("PW", "Palau");
        m.put("PS", "Palestine, State of");
        m.put("PA", "Panama");
        m.put("PG", "Papua New Guinea");
        m.put("PY", "Paraguay");
        m.put("PE", "Peru");
        m.put("PH", "Philippines");
        m.put("PN", "Pitcairn");
        m.put("PL", "Poland");
        m.put("PT", "Portugal");
        m.put("PR", "Puerto Rico");
        m.put("QA", "Qatar");
        m.put("RE", "Reunion");
        m.put("RO", "Romania");
        m.put("RU", "Russian Federation");
        m.put("RW", "Rwanda");
        m.put("BL", "Saint Barthelemy");
        m.put("SH", "Saint Helena, Ascension and Tristan da Cunha");
        m.put("KN", "Saint Kitts and Nevis");
        m.put("LC", "Saint Lucia");
        m.put("MF", "Saint Martin (French part)");
        m.put("PM", "Saint Pierre and Miquelon");
        m.put("VC", "Saint Vincent and the Grenadines");
        m.put("WS", "Samoa");
        m.put("SM", "San Marino");
        m.put("ST", "Sao Tome and Principe");
        m.put("SA", "Saudi Arabia");
        m.put("SN", "Senegal");
        m.put("RS", "Serbia");
        m.put("SC", "Seychelles");
        m.put("SL", "Sierra Leone");
        m.put("SG", "Singapore");
        m.put("SX", "Sint Maarten (Dutch part)");
        m.put("SK", "Slovakia");
        m.put("SI", "Slovenia");
        m.put("SB", "Solomon Islands");
        m.put("SO", "Somalia");
        m.put("ZA", "South Africa");
        m.put("GS", "South Georgia and the South Sandwich Islands");
        m.put("SS", "South Sudan");
        m.put("ES", "Spain");
        m.put("LK", "Sri Lanka");
        m.put("SD", "Sudan");
        m.put("SR", "Suriname");
        m.put("SJ", "Svalbard and Jan Mayen");
        m.put("SE", "Sweden");
        m.put("CH", "Switzerland");
        m.put("SY", "Syrian Arab Republic");
        m.put("TW", "Taiwan");
        m.put("TJ", "Tajikistan");
        m.put("TZ", "Tanzania");
        m.put("TH", "Thailand");
        m.put("TL", "Timor-Leste");
        m.put("TG", "Togo");
        m.put("TK", "Tokelau");
        m.put("TO", "Tonga");
        m.put("TT", "Trinidad and Tobago");
        m.put("TN", "Tunisia");
        m.put("TR", "Turkiye");
        m.put("TM", "Turkmenistan");
        m.put("TC", "Turks and Caicos Islands");
        m.put("TV", "Tuvalu");
        m.put("UG", "Uganda");
        m.put("UA", "Ukraine");
        m.put("AE", "United Arab Emirates");
        m.put("GB", "United Kingdom");
        m.put("US", "United States of America");
        m.put("UM", "United States Minor Outlying Islands");
        m.put("UY", "Uruguay");
        m.put("UZ", "Uzbekistan");
        m.put("VU", "Vanuatu");
        m.put("VE", "Venezuela");
        m.put("VN", "Viet Nam");
        m.put("VG", "Virgin Islands (British)");
        m.put("VI", "Virgin Islands (U.S.)");
        m.put("WF", "Wallis and Futuna");
        m.put("EH", "Western Sahara");
        m.put("YE", "Yemen");
        m.put("ZM", "Zambia");
        m.put("ZW", "Zimbabwe");
        CODE_TO_NAME = Collections.unmodifiableMap(m);
    }

    public static boolean isValidCode(String code) {
        return code != null && CODE_TO_NAME.containsKey(code.trim().toUpperCase());
    }

    public static String nameForCode(String code) {
        return code == null ? null : CODE_TO_NAME.get(code.trim().toUpperCase());
    }
}
