server.port=${SERVER_PORT:8082}
spring.application.name=reporting-service
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/transactionflow}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:transactionflow}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:transactionflow}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
producer.service.url=${PRODUCER_SERVICE_URL:http://localhost:8081}
hdfs.namenode.url=${HDFS_NAMENODE_URL:http://hdfs-namenode:9870}
management.endpoints.web.exposure.include=health,info,metrics
